### ISSUE TITLE
How do you disassemble the first instruction in a buffer of unknown length?

### ISSUE THREAD

**Issue by jessiepathfinder** [swojtasiak/fcml-lib#312]

**Comment by swojtasiak** [comment]
You have to disassemble code in chunks and every time a new chunk of code is available a new `DisassemblerContext` have to be created and passed to `disassemble`. You probably shouldn't disassemble the whole chunk to the last byte but move last 15 bytes or more to the next chunk in order to avoid problems related to dissemination of partial instructions.
